CC = g++

TAG = frame-buffer-test

HOME = ../../..

INC = -I $(HOME)/application/lib/include/

LIB = $(HOME)/application/lib/src/FrameBufferDev.cpp \
	$(HOME)/application/lib/src/IrayRgbImage.cpp \
	$(HOME)/application/lib/src/Bt656Merge.cpp \
	$(HOME)/application/lib/src/IrayCameraData.cpp \
		
SRC = main.cpp
		

#CFLAGS = -O3 -Wall -std=c99
CFLAGS = -O3 -Wall -ljpeg
CFLAGS += -lpthread -lrt

all:
	@$(CC) $(INC) $(LIB) $(SRC) -o $(TAG) $(CFLAGS)

clean:
	rm -rf $(TAG) *.o
